spring:
  datasource:
    url: jdbc:h2:~/data/eatgo
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    hibernate:
      ddl-auto: update
jwt:
  secret: 12345678901234567890123456789012

---

spring:
  config:
    activate:
      on-profile: test
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  datasource:
    url: jdbc:h2:mem:test
jwt:
  secret: 12345678901234567890123456789012


---

spring:
  config:
    activate:
      on-profile: mysql
  jpa:
    database: mysql
  datasource:
    url: jdbc:mysql://${MYSQL_HOST}:3306/${MYSQL_DATABASE}
    username: ${MYSQL_USER}
    password: ${MYSQL_PASSWORD}

jwt:
  secret: 12345678901234567890123456789012