spring:
  config:
    activate:
      on-profile: mysql
  jpa:
    database: mysql
  datasource:
    url: jdbc:mysql://${MYSQL_HOST}:3306/${MYSQL_DATABASE}
    username: ${MYSQL_USER}
    password: ${MYSQL_PASSWORD}

jwt:
  secret: 12345678901234567890123456789012